---
# Edit the filepaths and rename to master_config.yml
#
# data_directory is your clone of the 2021/data directory
# in the NIW_GoM_processing drive
# code_directory is your clone of the base directory
# of the SUNRISE-data-processing github
# most likely the directory this file is in
data_directory: "some_filepath"
code_directory: "some_other_filepath"
