% misc_cruise
%
clc; clear;
SAV=1;tic
iplot=1;
DAS = readtable('./MIDAS_001.txt');
%}

das.time=(DAS.Date+DAS.Time);

latchar = string(DAS.ADU800_GGA_Lat);
das.lat = str2double(extractBetween(latchar(:),1,2)) + str2double(extractBetween(latchar(:),3,12))/60;

lonchar = string(DAS.ADU800_GGA_Lon);
das.lon = -(str2double(extractBetween(lonchar(:),1,3)) + str2double(extractBetween(lonchar(:),4,13))/60);


das.heading_gyro = DAS.Sperry_MK1_Gyro_Hdg_deg;
das.heading_GPS = DAS.Furuno_SC50_GPS_Hdg_Hdg;
das.T = DAS.Thermosalinograph_Data_Temp;
das.S = DAS.Thermosalinograph_Data_Salinity;
das.cond = DAS.Thermosalinograph_Data_Conductivity;
das.ssnd = DAS.Thermosalinograph_Data_Sound_Velocity;
das.transm = DAS.Transmissometer_percent_DRV_VALUE;
das.fluo = DAS.Wetstar_Flourometer_microgperL_DRV_VALUE;
das.SPARvolt = DAS.SPAR_Voltage_DRV_VALUE;
das.SPARme = DAS.SPAR_Microeinsteins_DRV_VALUE;
das.airT = DAS.Air_Temp_1;
das.airT2 = DAS.Air_Temp_2;
das.RH = DAS.Rel_Humidity_1;
das.RH2 = DAS.Rel_Humidity_2;
das.baroP = DAS.BaromPress_1;
das.baroP2=DAS.BaromPress_2;
das.relwinddir = DAS.Rel_WindDir_1_Val;
das.relwindspd = DAS.Rel_WindDir_2;
das.relwinddir2 = DAS.Rel_WindDir_2;
das.truewinddir = DAS.TrueWindDirection_1_DRV_DIRECTION;
das.truewindspd = DAS.TrueWindDirection_1_DRV_SPEED;
das.truewinddir2 = DAS.True_Wind_2_DRV_DIRECTION;
das.truewindspd2 = DAS.True_Wind_2_DRV_SPEED;
das.truewindspd5sa = DAS.TWSpd_5sAvg2_DRV_VALUE;
das.LW = DAS.Radiometer_Feed__LongWaveRadiationWattsPerSquareMeter;
das.SW = DAS.Radiometer_Feed__ShortWaveRadiationFromPSPInWattsPerM_2;

das.readme=char('Data collected by the R/V Pelican onboard system for GoM 2019 cruise',...
    'time: in Matlab datenum format',...
    'lat, lon is degrees',...
    'heading_gyro: ship''s heading from the gyro, [degrees]',...
    'heading_GPS: ship''s heading from GPS [degrees]',...
    'T: temperature [deg C]',...
    'S: salinity [psu]',...
    'conductivity: [mS]',...
    'ssnd: speed of sound, [m\s]',...
    'transm: transmissometer, [%]',...
    'fluo: fluorometer [ug/L]',...
    'SPARvolt: [volt]',...
    'SPARme: [microeinsteins]',...
    'airT: air temperature [degC]',...
    'RH: relative humidity [%]',...
    'baroP: barometric pressure [mbar]',...
    'relwinddir: relative wind direction [degrees]',...
    'relwindspd: relative wind speed [kts]',...
    'truewinddir: true wind direction [degrees]',...
    'truewindspd: true wind speed [kts]',...
    'relwinddir2: relative wind direction [degrees]',...
    'relwindspd2: relative wind speed [kts]',...
    'truewindspd5sa: 5-second average of true wind speed [kts]',...
    'airT2: air temperature from [degC]',...
    'baroP2: barometric pressure from [mbar]',...
    'RH2: relative humidity from [%]',...
    'LW: long wave radiation [W/m2]',...
    'SW: short wave radiation [W/m2]');

save('./das.mat','das')

%save('/Users/aurelie/work/GoM_2019/data/das.mat','das')
